#!/bin/bash                                                                                                                                                                                                    
                                                                                                                                                                                                               
# Command line arguments given to this script                                                                                                                                                                  
args="$*"                                                                                                                                                                                                      
                                                                                                                                                                                                               
# Global S2I variable setup                                                                                                                                                                                    
source `dirname "$0"`/s2i-setup                                                                                                                                                                                
                                                                                                                                                                                                               
# Always include jolokia-opts, which can be empty if switched off via env                                                                                                                                      
export JAVA_OPTIONS="${JAVA_OPTIONS:+${JAVA_OPTIONS} }"
                                                                                                                                                                                                               
if [ -f "${DEPLOYMENTS_DIR}/bin/run.sh" ]; then
    echo "Starting the application using the bundled ${DEPLOYMENTS_DIR}/bin/run.sh ..."
    exec ${DEPLOYMENTS_DIR}/bin/run.sh $args ${JAVA_ARGS}
else                                                                                                                                                                                                           
    echo "Starting the Java application using ${DEPLOYMENTS_DIR}/run-java.sh ..."
    exec ${DEPLOYMENTS_DIR}/run-java.sh $args ${JAVA_ARGS}
fi
